import { Montserrat } from 'next/font/google'
import "../styles/globals.css"

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-sans',
  display: 'swap',
})

export const metadata = {
  title: "Javacourses",
  description: "Generated by javalzu!",
  icons: {
    icon: "/logo1.svg", // 
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${montserrat.variable} antialiased bg-gray-50 dark:bg-neutral-900`}>
        {children}
      </body>
    </html>
  )
}
