import { Montserrat } from 'next/font/google'
import "../src/shared/styles/globals.css"
import DebugClient from './debug-client'
import { QueryProvider } from '@/shared/providers/QueryProvider'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-sans',
  display: 'swap',
})

export const metadata = {
  title: "Javacourses",
  description: "Generated by javalzu!",
  icons: {
    icon: "/icons/logo1.png",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.variable} antialiased bg-gray-50 dark:bg-neutral-900`}
      >
        <QueryProvider>
          <DebugClient />
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}